### ISSUE TITLE
Play Game Button

### ISSUE THREAD

**Issue by pbateman828** [dmadisetti/gameFrame#6]
When the score as well as highscore is displayed at the end of flappy bird, doge and bowling.  The user is given a **play game** button that restarts the game. 

For pong, sadly this isn't working correctly.  The game doesn't restart. 

I have just been F5-ing it. For a fresh game.

**Comment by dmadisetti** [comment]
https://github.com/dmadisetti/gameFrame/pull/7/commits/349acef3ad25c53fb6736c9a406ad7b38f1787ec
